### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by robot00f** [gabrielg/periscope_api#13]
I do not know what i'm doing wrong
`ffmpeg -re -i /root/conejo.mp4 -acodec libmp3lame  -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 426x240 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv "rtmp://vidman-sa-east-1.periscope.tv:443/liveorigin?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0/EAlqDNwyozjeXxZP"`

CreateBroadcast I get this

`vidman-sa-east-1.periscope.tv","Shard":"EAlqDNwyozjeXxZP","Application":"vidmanlive","Region":"sa-east-1","stream_name":"2FVYy8t7xjCr5_gxYDPHPcYbBYp90cPeptV2ziWsWCs6TPoUFDqnPd6G9m8HPp4x_7dDmo6JXNoh2y0lI52zvg"},"protocol":"RTMPS","psp_version":[1,0,0],"host":"vidman-sa-east-1.periscope.tv","port":443,"application":"vidmanlive","stream_name":"EAlqDNwyozjeXxZP.2FVYy8t7xjCr5_gxYDPHPcYbBYp90cPeptV2ziWsWCs6TPoUFDqnPd6G9m8HPp4x_7dDmo6JXNoh2y0lI52zvg","credential":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbInJ0bXBzIl0sIkJyb2FkY2FzdElkIjoiMXlOR2FBWG52d1JHaiIsIkdyYW50VHlwZSI6IndyaXRlIiwiR3JhbnRlZEF0IjoxNDc5MTUyMzIzLCJHcmFudGVkVG8iOiIxZHZFT3JCZHFNbGpYIiwiZXhwIjoxNDc5MjM4NzIzfQ.rpqovmLgpYipqfS_fbpNjTk2bOTbA86wenMVFtxRtvM","private_protocol":"RTMPS","private_port":443`

**Comment by Pmmlabs** [comment]
@brunomoreno71 look at last commit date. This method stopped to work a long long time ago.
